services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd!
      - POSTGRES_DB=mydb
    ports:
      - 5434:5434
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: